version: 0.0
os: linux
files:
  source: /
  destination: /home/ubuntu
  overwrite: yes

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 755
hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 500
      runas: ubuntu
