version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu
    overwrite: yes

permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  AfterInstall:
    - location: scripts/after-deploy.sh
      timeout: 300
      runas: root
