version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/artgarden
    overwrite: yes

permissions:
  - object: /home/ubuntu/artgarden
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: deploy.sh
      timeout: 500
      runas: root
