version: 0.0
os: linux
files:
  source: /
  destination: /home/ubuntu
file_exists_behavior: OVERWRITE

permissions:
  - object: /home/ubuntu
    owner: root
    group: root

hooks:
  AfterInstall:
    - location: deploy.sh
      timeout: 2000
      runas: root
