name: deploy to S3

on:
  push:
    branches:
      - main

env:
  S3_BUCKET_NAME: artgarden
  CODE_DEPLOY_APPLICATION_NAME: codedeploy
  CODE_DEPLOY_DEPLOYMENT_GROUP_NAME: artgardenfordeploygroup

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code.
        uses: actions/checkout@v3
      - name: Check Node v
        run: node -v

      - name: Generate Environment Variables File
        run: |
          echo "NEXT_PUBLIC_KOPIS_URL=$KOPIS_URL" >> .env
          echo "NEXT_PUBLIC_KOPIS_KEY=$KOPIS_KEY" >> .env
          echo "NEXT_PUBLIC_BACKEND_URL=$BACKEND_URL" >> .env
        env:
          NEXT_PUBLIC_KOPIS_URL: ${{secrets.NEXT_PUBLIC_KOPIS_URL}}
          NEXT_PUBLIC_KOPIS_KEY: ${{secrets.NEXT_PUBLIC_KOPIS_KEY}}
          NEXT_PUBLIC_BACKEND_URL: ${{secrets.NEXT_PUBLIC_BACKEND_URL}}

      - name: Cache node modules
        uses: actions/cache@v3
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build next app
        run: npm run build

      - name: zip create
        run: |
          zip -qq -r --symlinks  ./artgarden.zip .
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3-node20
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 cp --region ap-northeast-2 ./artgarden.zip s3://$S3_BUCKET_NAME/artgarden.zip

      - name: Deploy For Development
        run: |
          aws deploy create-deployment \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --application-name ${{ env.CODE_DEPLOY_APPLICATION_NAME }} \
          --deployment-group-name ${{ env.CODE_DEPLOY_DEPLOYMENT_GROUP_NAME }} \
          --s3-location bucket=$S3_BUCKET_NAME,key=artgarden.zip,bundleType=zip
